C4Context
title System Context diagram for Internet Banking System

Person(Administrador, "Administrador", "Supervisiona o funcionamento")
Person(Teacher, "Professor","Publica as aulas")
Person(Student, "Aluno","Assiste às aulas")
System(System, "Sistema Educacional", "Permite o Aluno acesse a aula, o Professor publique a aula e o Administrador supervisione")

Enterprise_Boundary(Application, "Aplicação") {
 SystemDb(Bank, "Banco de Dados", "")
 SystemQueue(Back, "Backend", "")
 SystemQueue(Front, "Frontend", "")
}

Rel(Administrador, System,"Supervisionar")
Rel(Teacher, System,"Criar,Editar e Publicar")
Rel(Student, System,"Visualizar e Responder")
Rel(Bank,Back,"")
Rel(Back,Front,"")
Rel(Front,System,"")
Rel(System,Back,"")
